"""Builds an anime-style prompt and generates an image with provider fallback.

The fallback chain tries each configured image provider in order. When a
provider fails it logs the exact reason and emits a non-fatal warning alert
so provider health can be tracked. If every provider fails, it sends an alert
and returns an empty string so the run degrades gracefully to a text-only post.
"""
from collections.abc import Sequence

from . import notifier
from .logging_setup import get_logger
from .providers.image.base import ImageProvider

log = get_logger("image")


def _build_prompt(topic: str, style: str) -> str:
    return (
        f"A high-quality {style}-style illustration representing the topic: {topic}. "
        "Vibrant colors, clean composition, detailed, suitable for a social media post."
    )


def generate_image(
    providers: Sequence[ImageProvider],
    topic: str,
    style: str = "anime",
) -> str:
    """Try each provider in order. Returns an image ref, or "" if all fail.

    Never raises: image generation is best-effort so the post can still go out
    as text-only when no provider succeeds.
    """
    prompt = _build_prompt(topic, style)
    total = len(providers)
    for index, provider in enumerate(providers, start=1):
        name = type(provider).__name__
        try:
            result = provider.generate(prompt)
            if index > 1:
                log.info("Image generated by fallback provider %s.", name)
            else:
                log.info("Image generated by primary provider %s.", name)
            return result
        except Exception as exc:
            log.error("Image provider %s (%d/%d) failed: %s", name, index, total, exc)
            if index < total:
                nxt = type(providers[index]).__name__
                notifier.send_alert(
                    f"Image provider {name} failed ({exc}); falling back to {nxt}."
                )
    log.error("All %d image provider(s) failed; degrading to text-only.", total)
    notifier.send_alert(
        f"All {total} image provider(s) failed for topic {topic!r}; "
        "posting text-only."
    )
    return ""
